### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by iciarfernandez** [stat545ubc-2021/salihin_mda2#2]
Hey Salihin! Excellent work and congratulations on finishing your last project for STAT545 - I hope you enjoyed the class and feel confident with your data analysis skills! I was impressed with your last milestone, your plots are very readable and aesthetically nice, you took care to name the axes in a legible way, and to add titles. Your project also checks off all the boxes for tidy submission, you made sure that it would be easy to navigate for anyone visiting. All files are up to date and the knitted output renders properly and is viewable from GitHub, good job! A few minor comments:

- File and folder structure: .DS_Store and salihin_mda2.Rproj files don't need to be pushed to GitHub and they are not explained in the README either.
- Issues: This is **not** a requirement of the MDA and there are no deductions, but it is good practice to close issues when you are done with discussion (i.e., if you read the feedback and there is nothing that you would like to say / discussion has ended) - make sure to do that for future projects!

Please let me know if you have any questions!

Best wishes,
Icíar

**Comment by salihinsubhan** [comment]
Thank you so much for your guidance in 545A, I look forward to more of the same in 545B :)
